openapi: 3.0.1
tags:
  - name: Authorizations
    description: Everything about your Authorizations

paths:
  /api/v1/oauth/token:
    post:
      tags:
        - Authorizations
      summary: Get user token
      description: Get token
      requestBody:
        description: Oauth Body as object
        content:
          application/json:
            schema:
              properties:
                  id:
                    type: integer
                    format: int64
        required: true
      responses:
        '200':
          description: A successful response
          content: {}
        '400':
          description: Error Bad Request
          content: {
              "statusCode": 400,
              "errorMessage": "Invalid Grant Type",
              "errorCode": "Error",
              "data": {}
          }
